import getLatestDependencyVersion from "../../helpers/get-latest-dependency-version.js";
import { Packages } from "../../types.js";
import { join } from "path";
import { readFile, writeFile } from "fs/promises";
import { addToPackageJson } from "../../helpers/add-to-package-json";
import pathExists from "../../helpers/path-exists.js";
import mkdirp from "../../helpers/mkdirp.js";

const quaffComponents = [
  "QAvatar",
  "QBtn",
  "QCard",
  "QCardSection",
  "QCardActions",
  "QCheckbox",
  "QChip",
  "QCodeBlock",
  "QDialog",
  "QDrawer",
  "QFooter",
  "QIcon",
  "QInput",
  "QSelect",
  "QLayout",
  "QList",
  "QItem",
  "QItemSection",
  "QLinearProgress",
  "QRadio",
  "QRailbar",
  "QSeparator",
  "QTabs",
  "QTab",
  "QTable",
  "QToggle",
  "QToolbar",
  "QToolbarTitle",
  "QTooltip",
];

export default class AddAutoimportCommand {
  constructor(
    public projectDir: string,
    public language: string | null
  ) {}

  get usesTypescript() {
    return this.language === "typescript";
  }

  async execute() {
    await addToPackageJson(this.projectDir, {
      devDependencies: {
        [Packages.SVELTEKIT_AUTOIMPORT]: await getLatestDependencyVersion(
          Packages.SVELTEKIT_AUTOIMPORT
        ),
      },
    });

    await this.addToViteConfig();

    if (this.usesTypescript) {
      await this.addTypescriptDeclarations();
      await this.addTypescriptVscodeSettings();
    }
  }

  async addToViteConfig() {
    const filePath = join(this.projectDir, `vite.config.${this.usesTypescript ? "ts" : "js"}`);

    let contents = await readFile(filePath, "utf8");
    const importStatement = `import autoImport from 'sveltekit-autoimport';`;
    contents = contents.replace(/([\n\s]+export default)/, `\n${importStatement}$1`);

    contents = contents.replace(
      "sveltekit()",
      `
\t\tautoImport({
\t\t\tmodule: {
\t\t\t\t'@quaffui/quaff': [
${quaffComponents.map((name) => `\t\t\t\t'${name}',`).join("\n")}
\t\t\t\t]
\t\t\t}
\t\t}),
\t\tsveltekit()\n\t`
    );

    await writeFile(filePath, contents, "utf8");
  }

  async addTypescriptDeclarations() {
    const contents = `/* eslint-disable */
/* prettier-ignore */
// Auto generated by Quaff
export {}

declare global {
${quaffComponents
  .map((name) => `\tconst ${name}: typeof import('@quaffui/quaff')['${name}']`)
  .join("\n")}
}
`;

    await writeFile(join(this.projectDir, "src", "auto-imports.d.ts"), contents, "utf8");
  }

  async addTypescriptVscodeSettings() {
    const vscodeDir = join(this.projectDir, ".vscode");
    await mkdirp(vscodeDir);
    const vscodeSettingsPath = join(vscodeDir, "settings.json");

    const contents = (await this.tryReadJsonFile(vscodeSettingsPath)) || {};

    contents["svelte.plugin.svelte.compilerWarnings"] = {
      "missing-declaration": "ignore",
    };

    const contentsJson = JSON.stringify(contents, null, 2) + "\n";

    await writeFile(vscodeSettingsPath, contentsJson, "utf8");
  }

  async tryReadJsonFile(filePath: string) {
    try {
      if (!(await pathExists(filePath))) {
        return {};
      }

      const contentsRaw = await readFile(filePath, "utf8");
      return JSON.parse(contentsRaw) || {};
    } catch (e) {
      return {};
    }
  }
}
