import { join } from "path";
import { readFile, writeFile } from "fs/promises";
import { Packages, PackageVersions } from "../../types.js";
import addToPackageJson from "../../helpers/addToPackageJson.js";
import pathExists from "../../helpers/pathExists.js";
import mkdirp from "../../helpers/mkdirp.js";

const quaffComponents = [
  "QAvatar",
  "QBreadcrumbs",
  "QBreadcrumbsEl",
  "QBtn",
  "QIconBtn",
  "QCard",
  "QCardSection",
  "QCardActions",
  "QCheckbox",
  "QChip",
  "QCircularProgress",
  "QCodeBlock",
  "QDialog",
  "QDrawer",
  "QExpansionItem",
  "QFooter",
  "QHeader",
  "QHeaderTitle",
  "QIcon",
  "QInput",
  "QSelect",
  "QLayout",
  "QList",
  "QItem",
  "QItemSection",
  "QLinearProgress",
  "QMenu",
  "QRadio",
  "QRailbar",
  "QSeparator",
  "QTabs",
  "QTab",
  "QTable",
  "QSwitch",
  "QTooltip",
];

export default class AddAutoimportCommand {
  constructor(
    public projectDir: string,
    public language: string | null
  ) {}

  get usesTypescript() {
    return this.language === "typescript";
  }

  async execute() {
    await addToPackageJson(this.projectDir, {
      devDependencies: {
        [Packages.SVELTEKIT_AUTOIMPORT]: PackageVersions.SVELTEKIT_AUTOIMPORT,
      },
    });

    await this.addToViteConfig();

    if (this.usesTypescript) {
      await this.addTypescriptDeclarations();
      await this.addTypescriptVscodeSettings();
    }
  }

  async addToViteConfig() {
    const filePath = join(this.projectDir, `vite.config.${this.usesTypescript ? "ts" : "js"}`);

    let contents = await readFile(filePath, "utf8");
    const importStatements = `import autoImport from 'sveltekit-autoimport';
import { quaffCss } from '@quaffui/quaff/plugins/css';`;
    const pluginConfig = `autoImport({
\t\t\tconfigFile: false,
\t\t\tmodule: {
\t\t\t\t'@quaffui/quaff': [
${quaffComponents.map((name) => `\t\t\t\t'${name}',`).join("\n")}
\t\t\t\t]
\t\t\t}
\t\t}),
\t\tquaffCss(),`;

    contents = contents.replace(/([\n\s]+export default)/, `\n${importStatements}$1`);
    contents = contents.replace(/(\n\s*)sveltekit\(/, `$1${pluginConfig}$1sveltekit(`);

    await writeFile(filePath, contents, "utf8");
  }

  async addTypescriptDeclarations() {
    const contents = `/* eslint-disable */
/* prettier-ignore */
// Auto generated by Quaff
export {}

declare global {
${quaffComponents
  .map((name) => `\tconst ${name}: typeof import('@quaffui/quaff')['${name}']`)
  .join("\n")}
}
`;

    await writeFile(join(this.projectDir, "src", "auto-imports.d.ts"), contents, "utf8");
  }

  async addTypescriptVscodeSettings() {
    const vscodeDir = join(this.projectDir, ".vscode");
    await mkdirp(vscodeDir);
    const vscodeSettingsPath = join(vscodeDir, "settings.json");

    const contents = (await this.tryReadJsonFile(vscodeSettingsPath)) || {};

    contents["svelte.plugin.svelte.compilerWarnings"] = {
      "missing-declaration": "ignore",
    };

    const contentsJson = JSON.stringify(contents, null, 2) + "\n";

    await writeFile(vscodeSettingsPath, contentsJson, "utf8");
  }

  async tryReadJsonFile(filePath: string) {
    try {
      if (!(await pathExists(filePath))) {
        return {};
      }

      const contentsRaw = await readFile(filePath, "utf8");
      return JSON.parse(contentsRaw) || {};
    } catch {
      return {};
    }
  }
}
